int b = 4 + 4;
void main() {
    b + 3;
    4 + 4 - 6;
    93.0 + 5;
    3 + 5.0;
    float k = 2.0 * 20;
    write(k);
    write('-');
    k = k / 10;
    write(k);
    write('-');
    'a';
    'b';
    true;
    int a = 1;
    int b = a + 4;
    a = a + 7;
    b = b + 42 + 8;
    write(b);
    write(a);
    write('-');
    bool c = true && false;
    bool d = true && c;
    float num = a + b;
    write(num);
    write('-');
    write(1);
    write(2.0);
    write(true);
    write('-');
    int i1;
    write("Enter integer:");
    read(i1);
    write(i1);
    write("Enter float:");
    float f1;
    read(f1);
    write(f1);
    write("Enter char:");
    char c1;
    read(c1);
    write(c1);
}
